# Generated by Django 4.0.4 on 2022-08-02 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchId', models.CharField(max_length=50, null=True, unique=True)),
                ('gameDuration', models.CharField(max_length=50, null=True)),
                ('queueId', models.CharField(max_length=50, null=True)),
                ('mapName', models.CharField(max_length=50, null=True)),
                ('mapDesc', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50, null=True)),
                ('region', models.CharField(max_length=50, null=True)),
                ('level', models.CharField(max_length=50, null=True)),
                ('tier', models.CharField(max_length=50, null=True)),
                ('rank', models.CharField(max_length=50, null=True)),
                ('lp', models.CharField(max_length=50, null=True)),
                ('win', models.CharField(max_length=50, null=True)),
                ('lose', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Champ', models.CharField(max_length=50, null=True)),
                ('KDA', models.CharField(max_length=10, null=True)),
                ('TotalGold', models.IntegerField(blank=True, null=True)),
                ('SoloKill', models.IntegerField(blank=True, null=True)),
                ('Level', models.IntegerField(blank=True, null=True)),
                ('CS', models.IntegerField(blank=True, null=True)),
                ('MatchId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.matchdata')),
            ],
        ),
    ]
